# Generated by Django 3.2.6 on 2021-10-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_alter_superhero_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='identity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
