# Generated by Django 3.2.6 on 2021-10-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20211009_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='strength',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(max_length=200),
        ),
    ]
