# Generated by Django 3.2.6 on 2021-09-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('identity', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
